### ISSUE TITLE
Week 1 - Project Approval: Review Ticket

### ISSUE THREAD

**Issue by willili-ljw** [aidanywu/furious_five#17]
Theme all the information toward project approval.

Scrum Team Project Review
Design - [Wiki Theme, Brain Write & Wire Frame
](https://docs.google.com/presentation/d/1c807StJW4zLvx77AQM418lahMuPuvcK3G9xoHWW4eNY/edit?usp=sharing)(https://docs.google.com/presentation/d/1qvIGgLwRf2URoCJvR0v0YliYuhY6FBTTT5o3Ou0tQ3g/edit#slide=id.g103c9bc53ff_0_6)
Technicals - 10  to 12 key ideas 
Github - On Wiki containing Management Plan
Deployment - [Wiki Plan, Hardware and Frequency](https://github.com/aidanywu/furious_five/wiki/Hardware-and-Frequency?)
Scrum Board - [Assignments and Backlog](https://docs.google.com/presentation/d/1qvIGgLwRf2URoCJvR0v0YliYuhY6FBTTT5o3Ou0tQ3g/edit?usp=sharing)

Individual Create Task Understanding and Score, Notes, on TPT
TPT 0.0, Create Task ideas, notes, and research
1.3 Program Design and Development
1.4 Identifying and Correcting Errors

[Soren, Vaishavi, and William Li's Trio Share Journal](https://docs.google.com/document/d/1JlCWDvBfgdGk6yeL6dtcpMhvRKLAqF3XmNti3TT9wHY/edit?usp=sharing)
[William Wu and Aidan's Pair Share Journal](https://docs.google.com/document/d/1Byg2xdhazwebff4lFHdSSj-k-xkj035d9EHa7PSV_1A/edit)

**Comment by deimie** [comment]
Design - 1/1
Technicals - .7/1 Technical were hard to find and the wiki was a bit weird to navigate
Github - 1/1
Deployment - 1/1
Scrum Board - 1/1
