### ISSUE TITLE
Week 1: Journal Work (see description)

### ISSUE THREAD

**Issue by vaishavijay** [aidanywu/furious_five#22]
TPT 0.0, Create Task ideas, notes, and research
1.3 Program Design and Development
1.4 Identifying and Correcting Errors

**Comment by willcyber** [comment]
https://docs.google.com/document/d/1Byg2xdhazwebff4lFHdSSj-k-xkj035d9EHa7PSV_1A/edit
Aidan and William Pair Share Journal

**Comment by willcyber** [comment]
https://docs.google.com/document/d/1Byg2xdhazwebff4lFHdSSj-k-xkj035d9EHa7PSV_1A/edit
Aidan and William Pair Share Journal
