### ISSUE TITLE
Week 4 -Review Ticket (Aidan Wu)

### ISSUE THREAD

**Issue by willcyber** [aidanywu/furious_five#79]
1. Attendance, tutorial makeup if missing time, activity, individual questions, work habits, tutorial if behind.
2. Individual Runtime review on About Page progress/quality.
3. Individual Analytics (Issues with Tangibles, Commits)
4. CB progress, focus is on CB-exam MCQ test and improvement plan
5. Expertise in one or more of the following...  Procedures, Blueprint, Jekyll, Deployment Certbot, Databases, Wikie Policies, Branching strategies,	SCSS, Async with Fetch

**Comment by aidanywu** [comment]
Self Grade:

4/5 - a lot more PBL contributions, focus and work on code and technicals during class

Goals for next week:

1. Create user accounts with databases
2. Make calendar savable
