### ISSUE TITLE
Week 4 - Review Ticket (William Li)

### ISSUE THREAD

**Issue by vaishavijay** [aidanywu/furious_five#80]
Make your own personal review ticket, capture in your personal history for comparison when we do next review.
1. Attendance, tutorial makeup if missing time, activity, individual questions, work habits, tutorial if behind.
2. Individual Runtime review on About Page progress/quality.
3. Individual Analytics (Issues with Tangibles, Commits)
[4. CB progress, focus is on CB-exam MCQ test and improvement plan](https://docs.google.com/document/d/1JlCWDvBfgdGk6yeL6dtcpMhvRKLAqF3XmNti3TT9wHY/edit#bookmark=id.71ww8a4axioh)
5. Expertise in one or more of the following...  Procedures, Blueprint, Jekyll, Deployment Certbot, Databases, Wikie Policies, Branching strategies,	SCSS, Async with Fetch

**Comment by willili-ljw** [comment]
4/5
-more contribution to pbl, more techincals

Plan for next week:

- [x] finish OpenWeather API
- [ ] connect the weekly calendar to a database so it can save between browser sessions
- [ ] all the other stuff for next week (jekyll?)
